# Generated by Django 5.2.3 on 2025-07-12 22:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idProduto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('codigo_barras', models.CharField(help_text='Código de barras no padrão EAN-13 (13 dígitos)', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Código de barras deve conter exatamente 13 dígitos numéricos', regex='^[0-9]{13}$')])),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_fabricacao', models.DateField(verbose_name='Data de Fabricação')),
                ('lote', models.CharField(max_length=50, verbose_name='Número do Lote')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Preço de Custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Preço de Venda')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('estoque_minimo', models.PositiveIntegerField(verbose_name='Estoque Mínimo')),
                ('estoque_atual', models.PositiveIntegerField(verbose_name='Estoque Atual')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.categoria', verbose_name='Categoria')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.fornecedor', verbose_name='Fornecedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
        ),
    ]
