# Generated by Django 5.2.3 on 2025-07-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_categoria_usuario_fornecedor_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='ativo',
        ),
    ]
