# Generated by Django 5.2.3 on 2025-07-13 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_produto_ativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(default=1, max_length=255, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='fornecedor',
            unique_together={('nome', 'usuario')},
        ),
    ]
