# Generated by Django 5.2.3 on 2025-08-04 02:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Veículo')),
                ('tipo_combustivel', models.CharField(choices=[('diesel', 'Diesel'), ('gasolina', 'Gasolina')], max_length=10, verbose_name='Tipo de Combustível')),
                ('consumo_por_km', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Consumo de Combustível por KM (L/km)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora de Geração')),
                ('enderecos_otimizados', models.JSONField(verbose_name='Endereços na Ordem Otimizada')),
                ('coordenadas_otimizadas', models.JSONField(verbose_name='Coordenadas na Ordem Otimizada')),
                ('distancia_total_km', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Distância Total (km)')),
                ('tempo_estimado_minutos', models.IntegerField(verbose_name='Tempo Estimado (minutos)')),
                ('nome_motorista', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Motorista')),
                ('valor_rota', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Rota (R$)')),
                ('produtos_quantidades', models.JSONField(verbose_name='Produtos e Quantidades')),
                ('link_maps', models.URLField(max_length=500, verbose_name='Link do Google Maps')),
                ('status', models.CharField(choices=[('em_progresso', 'Em Progresso'), ('concluido', 'Concluído')], default='em_progresso', max_length=15, verbose_name='Status da Rota')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rotas.veiculo', verbose_name='Veículo Escolhido')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['-data_geracao'],
            },
        ),
    ]
