# Generated by Django 5.2.6 on 2025-09-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0005_add_preco_combustivel_usado'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='custo_rota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo da Rota (R$)'),
        ),
        migrations.AddField(
            model_name='rota',
            name='destino',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Destino (bairro/cidade)'),
        ),
        migrations.AddField(
            model_name='rota',
            name='lucro_rota',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Lucro da Rota'),
        ),
        migrations.AddField(
            model_name='rota',
            name='valor_total_vendas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Valor Total de Vendas'),
        ),
    ]
